services:
  mysql:
    image: mysql:8.4.0
    container_name: minibank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: minibank1234!
      MYSQL_DATABASE: minibank
      MYSQL_USER: minibank
      MYSQL_PASSWORD: minibank1234!
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/minibank
      SPRING_DATASOURCE_USERNAME: minibank
      SPRING_DATASOURCE_PASSWORD: minibank1234!
    ports:
      - "8080:8080"